#!/usr/bin/env bash

# Set default HDFS user if not set
if [[ -z "${HDFS_USER}" ]]; then
  export HDFS_USER=spark
fi

if [[ "${1}" = 'master' ]]; then
  # Start Spark Master
  exec spark-class org.apache.spark.deploy.master.Master -h $(hostname)
elif [[ "${1}" = 'worker' ]]; then
  # Start Spark Worker
  exec spark-class org.apache.spark.deploy.worker.Worker spark://$2
else
  echo "Invalid command '${1}'" >&2
  exit 1
fi
